name: Run all versions with custom HMC command
on:
  workflow_dispatch:
    inputs:
      headlessmc-command:
        description: 'Arguments for the headlessmc command.'
        required: false
        default: '-lwjgl -inmemory --jvm -Djava.awt.headless=true'
        type: string


jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew build

      - name: Delete dev jar
        run: rm headlessmc-launcher-wrapper/build/libs/headlessmc-launcher-*-dev.jar
      - name: Delete javadoc jar
        run: rm headlessmc-launcher-wrapper/build/libs/headlessmc-launcher-*-javadoc.jar
      - name: Delete sources jar
        run: rm headlessmc-launcher-wrapper/build/libs/headlessmc-launcher-*-sources.

      - name: Rename launcher jar
        run: mv headlessmc-launcher-wrapper/build/libs/headlessmc-launcher-*.jar headlessmc-launcher-wrapper/build/libs/headlessmc-launcher.jar
      - name: Copy launcher jar
        run: cp headlessmc-launcher-wrapper/build/libs/headlessmc-launcher.jar .

      - name: Upload Launcher Jar
        uses: actions/upload-artifact@v4
        with:
          name: launcher-jar
          path: ./headlessmc-launcher.jar

  run:
    strategy:
      matrix:
        version:
          - { mc: 1.21, type: lexforge, modloader: forge, regex: .*forge.*, java: 21 }
          - { mc: 1.21, type: neoforge, modloader: neoforge, regex: .*neoforge.*, java: 21 }
          - { mc: 1.21, type: fabric, modloader: fabric, regex: .*fabric.*, java: 21 }
          - { mc: 1.20.6, type: lexforge, modloader: forge, regex: .*forge.*, java: 21 }
          - { mc: 1.20.6, type: neoforge, modloader: neoforge, regex: .*neoforge.*, java: 21 }
          - { mc: 1.20.6, type: fabric, modloader: fabric, regex: .*fabric.*, java: 21 }
          - { mc: 1.20.4, type: lexforge, modloader: forge, regex: .*forge.*, java: 17 }
          - { mc: 1.20.4, type: neoforge, modloader: neoforge, regex: .*neoforge.*, java: 17 }
          - { mc: 1.20.4, type: fabric, modloader: fabric, regex: .*fabric.*, java: 17 }
          - { mc: 1.20.3, type: lexforge, modloader: forge, regex: .*forge.*, java: 17 }
          - { mc: 1.20.3, type: neoforge, modloader: neoforge, regex: .*neoforge.*, java: 17 }
          - { mc: 1.20.3, type: fabric, modloader: fabric, regex: .*fabric.*, java: 17 }
          - { mc: 1.20.2, type: lexforge, modloader: forge, regex: .*forge.*, java: 17 }
          - { mc: 1.20.2, type: neoforge, modloader: neoforge, regex: .*neoforge.*, java: 17 }
          - { mc: 1.20.2, type: fabric, modloader: fabric, regex: .*fabric.*, java: 17 }
          - { mc: 1.20.1, type: lexforge, modloader: forge, regex: .*forge.*, java: 17 }
          - { mc: 1.20.1, type: fabric, modloader: fabric, regex: .*fabric.*, java: 17 }
          - { mc: 1.19.4, type: fabric, modloader: fabric, regex: .*fabric.*, java: 17 }
          - { mc: 1.19.4, type: lexforge, modloader: forge, regex: .*forge.*, java: 17 }
          - { mc: 1.19.3, type: fabric, modloader: fabric, regex: .*fabric.*, java: 17 }
          - { mc: 1.19.3, type: lexforge, modloader: forge, regex: .*forge.*, java: 17 }
          - { mc: 1.19.2, type: fabric, modloader: fabric, regex: .*fabric.*, java: 17 }
          - { mc: 1.19.2, type: lexforge, modloader: forge, regex: .*forge.*, java: 17 }
          - { mc: 1.19.1, type: fabric, modloader: fabric, regex: .*fabric.*, java: 17 }
          - { mc: 1.19.1, type: lexforge, modloader: forge, regex: .*forge.*, java: 17 }
          - { mc: 1.19, type: fabric, modloader: fabric, regex: .*fabric.*, java: 17 }
          - { mc: 1.19, type: lexforge, modloader: forge, regex: .*forge.*, java: 17 }
          - { mc: 1.18.2, type: fabric, modloader: fabric, regex: .*fabric.*, java: 17 }
          - { mc: 1.18.2, type: lexforge, modloader: forge, regex: .*forge.*, java: 17 }
          - { mc: 1.17.1, type: fabric, modloader: fabric, regex: .*fabric.*, java: 16 }
          - { mc: 1.17.1, type: lexforge, modloader: forge, regex: .*forge.*, java: 16 }
          - { mc: 1.16.5, type: fabric, modloader: fabric, regex: .*fabric.*, java: 8 }
          - { mc: 1.16.5, type: lexforge, modloader: forge, regex: .*forge.*, java: 8 }
          - { mc: 1.12.2, type: lexforge, modloader: forge, regex: .*forge.*, java: 8 }
          - { mc: 1.8.9, type: lexforge, modloader: forge, regex: .*orge.*, java: 8 }
          - { mc: 1.7.10, type: lexforge, modloader: forge, regex: .*orge.*, java: 8 }
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    needs: build
    steps:
      - uses: actions/download-artifact@v4
      - name: Display structure of downloaded files
        run: ls -R
      - name: Copy launcher jar
        run: cp launcher-jar/headlessmc-launcher.jar .
      - name: Run the MC client
        uses: 3arthqu4ke/mc-runtime-test@2.1.0
        with:
          mc: ${{ matrix.version.mc }}
          modloader: ${{ matrix.version.modloader }}
          regex: ${{ matrix.version.regex }}
          java: ${{ matrix.version.java }}
          mc-runtime-test: ${{ matrix.version.type }}
          xvfb: false
          headlessmc-command: ${{ github.event.inputs.headlessmc-command }}
          download-hmc: false
